# Generated by Django 4.1.1 on 2022-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('contect', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
